undertaker/coverage: Fix segfaults in output mode 'cat'
This changes avoids crashes in the formatCommented output methods when
called on empty units. This can happen when the file is either empty or
if there is no code block after a conditional block

Change-Id: I03e19bf8de03e3d37ca0db17bb77da859ab3032c

diff --git a/undertaker/coverage-tests/run-tests b/undertaker/coverage-tests/run-tests
--- a/undertaker/coverage-tests/run-tests
+++ b/undertaker/coverage-tests/run-tests
@@ -42,6 +42,15 @@ else
     passed=$(( $passed + 1 ))
 fi
 
+# test formatCommented functionality
+total=$(( $total + 1 ))
+undertaker -q -j coverage -O exec:cat coverage-cat.c > coverage-cat.c.got
+if ! diff -q coverage-cat.c.got coverage-cat.c.expected; then
+    echo "FAILED: output for coverage-cat.c differs"
+else
+    passed=$(( $passed + 1 ))
+fi
+
 
 echo "$passed/$total checks passed"
 [ $passed -eq $total ] || exit 1
