python: Fix failure detection in python tests
This change aborts the build if a test fails. Before, failures where silently ignored.

Change-Id: I5da9a18ad02b7411f1d3f5f3265b072e22f25ea1

diff --git a/python/Makefile b/python/Makefile
--- a/python/Makefile
+++ b/python/Makefile
@@ -10,7 +10,9 @@ check: all
 	$(MAKE) -s clean-check
 	@for test in vamos/*/*_test.py vamos/*_test.py; do \
 	   echo "Running python unittest $$test"; \
-	   env PATH="$(SEARCHPATH)" PYTHONPATH=$(CURDIR) python "$$test"; \
+	   if ! env PATH="$(SEARCHPATH)" PYTHONPATH=$(CURDIR) python "$$test"; then \
+	       echo "FAIL: $$test"; exit 1; \
+	   fi; \
 	done
 	cd validation && env PATH="$(SEARCHPATH)" ./test-suite
 	$(MAKE) -s pylint
